# Generated by Django 5.2 on 2026-02-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_skill_remove_enquiry_id_alter_enquiry_contactno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='contactno',
            field=models.CharField(max_length=15),
        ),
    ]
