# Generated by Django 5.2 on 2026-02-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_enquiry_id_alter_enquiry_contactno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
